// <auto-generated />
using System;
using LocaGuest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocaGuest.Infrastructure.Migrations
{
    [DbContext(typeof(LocaGuestDbContext))]
    [Migration("20251209105507_AddPaymentDueDayToContract")]
    partial class AddPaymentDueDayToContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.Addendum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachedDocumentIds")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NewCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewClauses")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NewEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NewRent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NewRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OccupantChanges")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldClauses")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OldEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldRent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OldRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignatureStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Addendums");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Charges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentIRL")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomClauses")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConflict")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PreviousIRL")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RenewedContractId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RenterTenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RenterTenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.ContractPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("contract_payments", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.DocumentAggregate.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssociatedTenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.InventoryAggregate.InventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralObservations")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RenterTenantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("RenterTenantId");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TenantPresent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("RenterTenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("inventory_entries", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.InventoryAggregate.InventoryExit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinancialNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralObservations")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InventoryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OwnerCoveredAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RenterTenantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("RenterTenantId");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TenantPresent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalDeductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("InventoryEntryId");

                    b.HasIndex("RenterTenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("inventory_exits", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.OrganizationAggregate.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionPlan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PaymentAggregate.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("ContractId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PaymentAggregate.RentInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DueDate");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("ContractId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("RentInvoices", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PropertyAggregate.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AsbestosDiagnosticDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedTenantCodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CadastralReference")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CondominiumCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DpeRating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DpeValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ElectricDiagnosticDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ElectricDiagnosticExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpZone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GasDiagnosticDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GasDiagnosticExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("GesRating")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasAsbestos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasParking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumStay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumStay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupiedRooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PropertyTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Surface")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalRooms")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalWorksAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PropertyAggregate.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PropertyAggregate.PropertyRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CurrentContractId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Surface")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentContractId");

                    b.HasIndex("PropertyId");

                    b.ToTable("property_rooms", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.RentabilityScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnnualAppreciation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CapitalGainsTax")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChargesIncrease")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CondoFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CrlApplicable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeferredMonths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeferredType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeficitCarryForward")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepreciationYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EarlyRepaymentPenalty")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ExitMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FurnitureCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FurnitureDepreciationYears")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GuaranteedRent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HighSeasonMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HoldYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Horizon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeNotaryInLoan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeRenovationInLoan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indexation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndexationRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Insurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsBase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LandValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ManagementFees")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MarginalTaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NotaryFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OtherRevenues")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ParkingRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlannedCapexJson")
                        .HasColumnType("text");

                    b.Property<decimal>("PropertyTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RecoverableCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RelocationIncrease")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RenovationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("text");

                    b.Property<bool>("SeasonalityEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SellingCosts")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SocialContributions")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StorageRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Surface")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetCapRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TargetPricePerSqm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxRegime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VacancyRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("TenantId", "UserId", "IsBase");

                    b.ToTable("rentability_scenarios", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.ScenarioComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RentabilityScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RentabilityScenarioId");

                    b.ToTable("ScenarioComment");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.ScenarioShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("ScenarioId", "SharedWithUserId");

                    b.ToTable("scenario_shares", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.ScenarioVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("scenario_versions", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAdvancedComparison")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasApiAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasApiReadWrite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDedicatedSupport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEmailNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPrioritySupport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPrivateTemplates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSlackIntegration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSso")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTeamTemplates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUnlimitedAi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUnlimitedExports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUnlimitedVersioning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWebhooks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAiSuggestionsPerMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxExportsPerMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxScenarios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxShares")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTeamMembers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxVersionsPerScenario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxWorkspaces")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripeAnnualPriceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeMonthlyPriceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnnual")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeLatestInvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("StripeSubscriptionId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.UsageAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "Dimension", "PeriodYear", "PeriodMonth")
                        .IsUnique();

                    b.ToTable("usage_aggregates", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TenantId", "SubscriptionId");

                    b.ToTable("usage_events", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.TenantAggregate.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MoveInDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.UserAggregate.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowTracking")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeaderNavigation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MonthlyReports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NewReservations")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PaymentReminders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SidebarNavigation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmsAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Analytics.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("PageName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EventType", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("TenantId", "UserId", "Timestamp");

                    b.ToTable("tracking_events", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Entities.InvitationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("invitation_tokens", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Entities.TenantSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityPrefix")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "EntityPrefix");

                    b.HasIndex("TenantId");

                    b.ToTable("tenant_sequences", (string)null);
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.Addendum", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.ContractAggregate.Contract", null)
                        .WithMany("Addendums")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.Contract", b =>
                {
                    b.OwnsMany("LocaGuest.Domain.Aggregates.ContractAggregate.RequiredDocument", "RequiredDocuments", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsProvided")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSigned")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContractId", "Type");

                            b1.ToTable("contract_required_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("RequiredDocuments");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.ContractPayment", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.ContractAggregate.Contract", null)
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.InventoryAggregate.InventoryEntry", b =>
                {
                    b.OwnsMany("LocaGuest.Domain.Aggregates.InventoryAggregate.InventoryItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("InventoryEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoomName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElementName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Comment")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Condition")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PhotoUrls")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InventoryEntryId", "RoomName", "ElementName");

                            b1.ToTable("inventory_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InventoryEntryId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.InventoryAggregate.InventoryExit", b =>
                {
                    b.OwnsMany("LocaGuest.Domain.Aggregates.InventoryAggregate.Degradation", "Degradations", b1 =>
                        {
                            b1.Property<Guid>("InventoryExitId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoomName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElementName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("EstimatedCost")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<bool>("IsImputedToTenant")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PhotoUrls")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InventoryExitId", "RoomName", "ElementName");

                            b1.ToTable("inventory_degradations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InventoryExitId");
                        });

                    b.OwnsMany("LocaGuest.Domain.Aggregates.InventoryAggregate.InventoryComparison", "Comparisons", b1 =>
                        {
                            b1.Property<Guid>("InventoryExitId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoomName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElementName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Comment")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("EntryCondition")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ExitCondition")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PhotoUrls")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InventoryExitId", "RoomName", "ElementName");

                            b1.ToTable("inventory_comparisons", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InventoryExitId");
                        });

                    b.Navigation("Comparisons");

                    b.Navigation("Degradations");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PropertyAggregate.PropertyImage", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.PropertyAggregate.Property", null)
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PropertyAggregate.PropertyRoom", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.PropertyAggregate.Property", null)
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.ScenarioComment", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.RentabilityAggregate.RentabilityScenario", null)
                        .WithMany("Comments")
                        .HasForeignKey("RentabilityScenarioId");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.ScenarioShare", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.RentabilityAggregate.RentabilityScenario", null)
                        .WithMany("Shares")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.ScenarioVersion", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.RentabilityAggregate.RentabilityScenario", null)
                        .WithMany("Versions")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.Subscription", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.SubscriptionAggregate.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.UsageEvent", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.SubscriptionAggregate.Subscription", null)
                        .WithMany("UsageEvents")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocaGuest.Domain.Entities.InvitationToken", b =>
                {
                    b.HasOne("LocaGuest.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("LocaGuest.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("LocaGuest.Domain.Aggregates.OrganizationAggregate.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.ContractAggregate.Contract", b =>
                {
                    b.Navigation("Addendums");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.PropertyAggregate.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.RentabilityAggregate.RentabilityScenario", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Shares");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LocaGuest.Domain.Aggregates.SubscriptionAggregate.Subscription", b =>
                {
                    b.Navigation("UsageEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
