// <auto-generated />
using LocaGuest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocaGuest.Infrastructure.Migrations
{
    [DbContext(typeof(LocaGuestDbContext))]
    [Migration("20251225201500_AddReservedRoomsToProperties")]
    partial class AddReservedRoomsToProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // NOTE: This file is intentionally minimal; the authoritative model is in LocaGuestDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
